### ISSUE TITLE
cannot create class "Action.SortAction" [Plugin: com.armandakopian.lifecyclesorter]

### ISSUE THREAD

**Issue by the4thfloor** [armandAkop/Lifecycle-Sorter#1]
It sounds good but it isn't working with Android Studio 1.2.1.1

```
cannot create class "Action.SortAction" [Plugin: com.armandakopian.lifecyclesorter]
com.intellij.diagnostic.PluginException: cannot create class "Action.SortAction" [Plugin: com.armandakopian.lifecyclesorter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:516)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:496)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:125)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
	at javax.swing.JMenu.setSelected(JMenu.java:294)
	at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: Action/SortAction : Unsupported major.minor version 51.0 [Plugin: com.armandakopian.lifecyclesorter]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 35 more
Caused by: java.lang.UnsupportedClassVersionError: Action/SortAction : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 41 more
```

**Comment by armandAkop** [comment]
What OS are you on?

**Comment by the4thfloor** [comment]
I use it on Mac OS 10.10.3 with Java 1.8

**Comment by armandAkop** [comment]
Hmm I've had this issue with OSX. Not sure yet if it's purely a Java problem or there is something else I need to configure in my project. Thanks for the feedback.

**Comment by the4thfloor** [comment]
I found it. I have Java 1.8 on my Mac but Android Studio ran with Java 1.6 :-(

**Comment by armandAkop** [comment]
I updated the plugin to be compatible with Java 1.6 so it won't be necessary to make changes on your end. I tested it on the only Macbook that I had access to and it seems to work. Please let me know if you continue to have this issue.
